language: r
warnings_are_errors: true
sudo: required
before_install:
- echo "TRAVIS BUILD ID"
- echo ${TRAVIS_BUILD_ID}
- echo "TRAVIS JOB ID"
- echo ${TRAVIS_JOB_ID}
- hostname
- users
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'covr::coveralls()'
- Rscript -e 'devtools::build(binary = FALSE)'
- Rscript -e 'devtools::build(binary = TRUE)'


deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true    
  api_key:
    secure: Q9EDWwhZuTOj/ppYq/ItgKVfD2ob8LRY+EA28nDIEJVHW+xXG1ydhXA2V7dmBDKMv1HAlvGrBYd+tVXv1UomvA7La24aHDedLoSR/QTPm0Q9VCf/rvVTP0COLlLcV5KzN4WBu57phw06mO1D9KWEnXKvD8W4bAlpjsvXzbxfYggllysVjXZTuiiJMwXtTxOJmke14HmoL5qUjJhx6L/i66Gk/dqEj+BeTNuJ4mQAZuXQ5gzY0dhc2mOfhtCx1DL1d2mjyH1S4aCWv1YilnRHt6swQ3EbMm8QBT2r0k8W4Ayj/PJNNK1miB8boAz0s/TtVUxqbJb663FykBFq9h4FtMDYhZwG1ZVqxod9CWZIM7EC2u8nryRyRL3pIEuN/Zcsy8t74EM+Ckyr5XX2LCXUyBegz9FYCcmHePlDHYwH8DfyJyiXlE+aHzGnaR7OXk8E8CSFvn5cQQX3dPLpJIKQwXFcf/Zia2k+arpS1HRouDFTRbmAlf9z6RJl0gnJYVLtrW+r9Hz402owMPpH7Ig2Ray4f1rLmmuIr2HLpEyTCPHdv3wPDpkxmE38+FGYUKYorYJtNvUd5tPbD3yvjPXdG9uzbJVbVToeHx1nlRKOWQ3d1L6m4uonM93DwdqPsoQnR/POOiCjeudWObiRKDTD9U1E/FzLRcKGfYaT8YSQSDg=
  file: neurobase*.t*gz
  on:
    tags: true    
    repo: muschellij2/neurobase