# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

deploy:
  provider: GitHub
  description: 'Windows Binary'
  auth_token:
    secure: Q9EDWwhZuTOj/ppYq/ItgKVfD2ob8LRY+EA28nDIEJVHW+xXG1ydhXA2V7dmBDKMv1HAlvGrBYd+tVXv1UomvA7La24aHDedLoSR/QTPm0Q9VCf/rvVTP0COLlLcV5KzN4WBu57phw06mO1D9KWEnXKvD8W4bAlpjsvXzbxfYggllysVjXZTuiiJMwXtTxOJmke14HmoL5qUjJhx6L/i66Gk/dqEj+BeTNuJ4mQAZuXQ5gzY0dhc2mOfhtCx1DL1d2mjyH1S4aCWv1YilnRHt6swQ3EbMm8QBT2r0k8W4Ayj/PJNNK1miB8boAz0s/TtVUxqbJb663FykBFq9h4FtMDYhZwG1ZVqxod9CWZIM7EC2u8nryRyRL3pIEuN/Zcsy8t74EM+Ckyr5XX2LCXUyBegz9FYCcmHePlDHYwH8DfyJyiXlE+aHzGnaR7OXk8E8CSFvn5cQQX3dPLpJIKQwXFcf/Zia2k+arpS1HRouDFTRbmAlf9z6RJl0gnJYVLtrW+r9Hz402owMPpH7Ig2Ray4f1rLmmuIr2HLpEyTCPHdv3wPDpkxmE38+FGYUKYorYJtNvUd5tPbD3yvjPXdG9uzbJVbVToeHx1nlRKOWQ3d1L6m4uonM93DwdqPsoQnR/POOiCjeudWObiRKDTD9U1E/FzLRcKGfYaT8YSQSDg=
  artifact: \*_*.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
    
