# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

deploy:
  provider: GitHub
  description: 'Windows Binary'
  auth_token:
    secure: rYy10bfIBZE0W+6VnNSJ53xhyD5s9DaLBf1jJiqKoMNc0YSOSC6QtQamn9XYWZkRR2xNzDZs1pYhSQJox77qFFWx4pucEQCLTeOVneQF5ataVqJ5TMY8lFl2XPE2QJsEITC7zrrB/M+aEwCJoq22vjN2XtbnOTdnumNnrYJDqmJNn3LxVBRWGm+PqWRvJBFdMCbtYSbb/SyZ7pqZqAisydABtj7o3y7IR1VG/cNn8eFNdJ95tNaU9ArqWsMz/rGCdCQ2U+tZefuf/PaVMuGy3/l8q8EhXydO1qQmuRJ9fIyuX6A0Fk8AF8muuIxzJVP1E+jOeCdCRjPdedgYo/DvTtLqzP16UQ5IW+qwM2c/scQxZ4qaDQJqvNymqMVWnIXcR9AJLpS0CwHUw2QQIgi9efSH/KToHCwAxUD/uhd2HRjHc9r020iIbJytcBwOHWYsr9vq1/Pa/5Kq1PtdBOIRqv2MCqxTwstBtox0Y1fHyuqiLzyPIsCAKVFE6KJalVDQ6cpR/Rz0MKwNpHqdxAvMpCCoQcP5p/ADacosHZTDJwSlhNF1UHzDjFzLCAn0jbtroe+nqDCJtPVsoo1wjOL7xXYSh5FlakhkR3L/T7NKkPjpBtaPPjychIHqo991XraPel2JSYAH5qG5AGNscm4Z7GR3v5D7nsQWH++ulAxkqrU=
  artifact: \*_*.zip
  draft: false
  prerelease: false
  tag: $(appveyor_repo_tag_name)
  on:
    appveyor_repo_tag: true
    
